name: weather_app
description: description
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.1.5 <4.0.0'

dependencies:
  flutter_bloc: ^8.1.3
  flutter_svg: ^2.0.9
  dio: ^5.4.0
  flutter_screenutil: ^5.9.0
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
